//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezerwacje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rezerwacje()
        {
            this.zarezerwowane_miejsca = new HashSet<zarezerwowane_miejsca>();
        }
    
        public int id_rezerwacji { get; set; }
        public int id_seansu { get; set; }
        public string typ_rezerwacji { get; set; }
        public string imie_klienta { get; set; }
        public string nr_telefonu { get; set; }
        public string nazwisko_klienta { get; set; }
        public bool czy_oplacone { get; set; }
        public System.DateTime data_dokonania_rezerwacji { get; set; }
    
        public virtual seanse seanse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zarezerwowane_miejsca> zarezerwowane_miejsca { get; set; }
    }
}
