//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;
    
    public partial class seanse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seanse()
        {
            this.rezerwacje = new HashSet<rezerwacje>();
            this.zarezerwowane_miejsca = new HashSet<zarezerwowane_miejsca>();
        }
    
        public int id_seansu { get; set; }
        public int id_filmu { get; set; }
        public int id_sali { get; set; }
        public System.DateTime czas_rozpoczecia { get; set; }
    
        public virtual filmy filmy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rezerwacje> rezerwacje { get; set; }
        public virtual sale sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zarezerwowane_miejsca> zarezerwowane_miejsca { get; set; }
    }
}
